name: Examples Check
on:
  pull_request:
    paths:
      - "examples/src/**"
      - "proto/**"
      - ".github/workflows/examples.yml"
env:
  WORKDIR: examples
jobs:
  Examples_Check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: ./.github/actions/mise
        with:
          workdir: ${{ env.WORKDIR }}
      - uses: ./.github/actions/python
        with:
          workdir: ${{ env.WORKDIR }}
      - name: Install Dependencies
        run: |
          mise //${{ env.WORKDIR }}:deps
      - name: TypeCheck
        run: |
          uv run mypy .
      - name: Lint
        run: |
          uv run ruff check .
      - name: Format
        run: |
          uv run ruff format . --check --diff
