name: GithubAction Check
on:
  pull_request:
    paths:
      - ".github/**/*.yml"
      - ".github/**/*.yaml"
jobs:
  GithubAction_Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/mise
        with:
          workdir: .
      - name: Run actionlint
        run: |
          mise run action_lint
