name: Test Protobuf Definitions

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'proto/**'
      - 'scripts/**'
      - '.github/workflows/test_protos.yml'
  pull_request:
    paths:
      - 'proto/**'
      - 'scripts/**'
      - '.github/workflows/test_protos.yml'
  workflow_dispatch:

jobs:
  validate-protos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: ./.github/actions/mise

      - name: Lint Proto
        run: |
          buf format --exit-code -d --error-format github-actions
          buf lint --error-format github-actions

      - name: Run Code Generation Test
        run: ./scripts/test_codegen.sh
